[workspace]
members = [
    "walicord",
    "walicord-application",
    "walicord-calc",
    "walicord-domain",
    "walicord-i18n",
    "walicord-infrastructure",
    "walicord-interpreter",
    "walicord-parser",
    "walicord-presentation"
]
resolver = "3"

[workspace.lints.clippy]
uninlined_format_args = "deny"
