[workspace]
members = [
    "walicord",
    "walicord-calc",
    "walicord_core",
    "walicord_interpreter",
    "walicord-parser"
]
resolver = "3"

[workspace.lints.clippy]
uninlined_format_args = "deny"
