[package]
name = "walicord-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8.0.0"
smallvec = "1.15.1"
thiserror = "2.0.17"

[dev-dependencies]
rstest = "0.26.1"

[features]
default = ["ja"]
ja = []
en = []
