[package]
name = "walicord-interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
walicord-core = { path = "../walicord-core" }
walicord-parser = { path = "../walicord-parser" }

[features]
default = ["microlp"]
microlp = ["walicord-core/microlp"]
coin_cbc = ["walicord-core/coin_cbc"]